# Generated by Django 3.1.4 on 2020-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Описание'),
        ),
    ]
